config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/summon', to: 'home#summon'

  resources :ranks
  resources :constellations
  resources :effects
  resources :characters do
    resources :stats
    resources :skills
    resources :cosmos_sets
    get 'search', on: :collection
  end
  resources :banners, only: %i[index new create show]

  resources :cosmo_basics
  resources :cosmo_types
  resources :cosmos
  get 'eighth_sense', to: 'home#eighth_sense'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'summon/markers', to: 'summon#markers'
      get 'summon/random', to: 'summon#random'
    end
  end
end

app/models/cosmos_set.rb
# frozen_string_literal: true

class CosmosSet < ApplicationRecord
  belongs_to :character

  def cosmos
    cosmos_ids.map { |cosmo_id| Cosmo.find(cosmo_id) }
  end
end

app/controllers/cosmos_sets_controller.rb
# frozen_string_literal: true

class CosmosSetsController < ApplicationController
  before_action :find_character
  before_action :prepare, only: %i[new edit]
  before_action :authenticate_admin

  def new
    @cosmos_set = CosmosSet.new
  end

  def create
    @cosmos_set = CosmosSet.new(cosmos_set_params)
    character = Character.find(params[:character_id])
    if @cosmos_set.save
      flash[:success] = 'Set de Cosmos criado com sucesso'
    else
      flash[:error] = 'Algo deu errado'
    end
    redirect_to character
  end

  def edit
    @cosmos_set = CosmosSet.find(params[:id])
  end

  def update
    @cosmos_set = CosmosSet.find(params[:id])
    if @cosmos_set.update(cosmos_set_params)
      flash[:success] = 'Set de Cosmos atualizado com sucesso'
      redirect_to @character
    else
      flash[:error] = 'Algo deu errado'
      render 'edit'
    end
  end

  def destroy
    @cosmos_set = CosmosSet.find(params[:id])
    if @cosmos_set.destroy
      flash[:success] = 'Set de Cosmos deletado com sucesso.'
    else
      flash[:error] = 'Algo deu errado'
    end
    redirect_to @character
  end

  private

  def cosmos_set_params
    params.require(:cosmos_set).permit(cosmos_ids: [])
          .merge(character_id: params[:character_id])
  end

  def prepare
    @character = Character.find(params[:character_id])
    @cosmos = Cosmo.all.order(name: :asc)
    @solar = @cosmos.where(cosmo_type: CosmoType.find_by(name: 'Solar'))
    @lunar = @cosmos.where(cosmo_type: CosmoType.find_by(name: 'Lunar'))
    @stellar = @cosmos.where(cosmo_type: CosmoType.find_by(name: 'Estelar'))
    @legendary = @cosmos.where(cosmo_type: CosmoType.find_by(name: 'Lendário'))
  end

  def find_character
    @character = Character.find(params[:character_id])
  end
end

app/views/cosmos_sets/_cosmos_set.html.erb
<div id="cosmos_set">
  <h4 class="text-center">Cosmos Recomendados</h4>
  <%= link_to  "Cadastrar Set de Cosmos", new_character_cosmos_set_path(@character), class: 'admin' %>

  <% @character.cosmos_sets.each do |cosmos_set| %>
  <div class="card-glow mb-4 mx-auto p-1" style="max-width: 300px;">
    <div class="row m-0 p-0">

      <% cosmos_set.cosmos.each do |cosmo| %>
        <div class="col-3 py-2">
          <% if cosmo.picture.attached? %>
            <%= image_tag cosmo.picture, class: 'img-fluid', title: cosmo.name %>
          <% end %>
        </div>
      <% end %>

      <div class="admin">
        <%= link_to  fa_icon("edit 2x"), edit_character_cosmos_set_path(@character, cosmos_set), class: 'edit' %>
        <%= link_to  fa_icon("trash 2x"), character_cosmos_set_path(@character, cosmos_set), method: :delete,
        data: {confirm: "Remover o Set de Cosmos?"}, class: 'delete text-danger' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cosmos_sets/_cosmos_sets.html.erb
<div id="cosmos_set">
  <h4 class="text-center">Cosmos Recomendados</h4>
  <%= link_to  "Cadastrar Set de Cosmos", new_character_cosmos_set_path(@character), class: 'admin' %>

  <% cosmos_sets.each do |cosmos_set| %>
  <div class="card-glow mb-4 mx-auto p-1" style="max-width: 300px;">
    <div class="row m-0 p-0">

      <% cosmos_set.cosmos.each do |cosmo| %>
        <div class="col-3 py-2">
          <% if cosmo.picture.attached? %>
            <%= image_tag cosmo.picture, class: 'img-fluid', title: cosmo.name %>
          <% end %>
        </div>
      <% end %>

      <div class="admin">
        <%= link_to 'Editar', edit_character_cosmos_set_path(@character, cosmos_set), class: 'edit' %>
        <%= link_to 'Deletar', character_cosmos_set_path(@character, cosmos_set), method: :delete,
        data: {confirm: "Remover o Set de Cosmos?"}, class: 'delete text-danger' %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cosmos_sets/edit.html.erb
<h1>Editando o set de cosmos</h1>
<div class="card text-dark p-3">
  <%= form_for [@character, @cosmos_set] do |f| %>
    <div class="row">
      <div class="form-group col-lg-3">
        <h5>Lendário</h5>
        <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@legendary, "id", "name"), class: 'form-control' %>
      </div>
      <div class="form-group col-lg-3">
        <h5>Solar</h5>
        <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@solar, "id", "name"), class: 'form-control' %>
      </div>
      <div class="form-group col-lg-3">
        <h5>Lunar</h5>
        <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@lunar, "id", "name"), class: 'form-control' %>
      </div>
      <div class="form-group col-lg-3">
        <h5>Estelar</h5>
        <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@stellar, "id", "name"), class: 'form-control' %>
      </div>
    </div>
    <%= f.submit 'Enviar', class: 'btn btn-success float-right' %>
    <%= link_to 'Voltar', @character, class: 'btn btn-primary' %>
  <% end %>
</div

app/views/cosmos_sets/new.html.erb
<h1>Novo Set de Cosmos</h1>
<div class="card">
  <%= form_for [@character, @cosmos_set] do |f| %>
  <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@legendary, "id", "name")%>
    <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@solar, "id", "name")%>
    <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@lunar, "id", "name")%>
    <%= select_tag "cosmos_set[cosmos_ids][]", options_from_collection_for_select(@stellar, "id", "name")%>
    <%= f.submit 'Enviar' %>
  <% end %>
</div