config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/summon', to: 'home#summon'

  resources :ranks
  resources :constellations
  resources :effects
  resources :characters do
    resources :stats
    resources :skills
    resources :cosmos_sets
    get 'search', on: :collection
  end
  resources :banners, only: %i[index new create show]

  resources :cosmo_basics
  resources :cosmo_types
  resources :cosmos
  get 'eighth_sense', to: 'home#eighth_sense'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'summon/markers', to: 'summon#markers'
      get 'summon/random', to: 'summon#random'
    end
  end
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord
  belongs_to :character
  has_one_attached :picture
  has_and_belongs_to_many :effects
  validates :name, presence: true

  enum kind: { default: 0, cloth: 5 }
end

app/controllers/skills_controller.rb
# frozen_string_literal: true

class SkillsController < ApplicationController
  before_action :authenticate_admin

  def new
    @character = Character.find(params[:character_id])
    @skill = Skill.new
    @effects = Effect.all.order(name: :asc)
  end

  def create
    @character = Character.find(params[:character_id])
    @skill = @character.skills.new(skill_params)
    if @skill.save
      flash[:success] = 'Habilidade criada com sucesso'
      redirect_to @character
    else
      flash[:error] = 'Não foi possível criar habilidade'
      @effects = Effect.all.order(name: :asc)
      render :new
    end
  end

  def edit
    @character = Character.find(params[:character_id])
    @skill = @character.skills.find(params[:id])
    @effects = Effect.all.order(name: :asc)
  end

  def update
    @character = Character.find(params[:character_id])
    @skill = @character.skills.find(params[:id])
    if @skill.update(skill_params)
      flash[:success] = 'Habilidade atualizada com sucesso'
      redirect_to @character
    else
      flash[:error] = 'Algo deu errado'
      render 'edit'
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    character = Character.find(params[:character_id])
    if @skill.destroy
      flash[:success] = 'Habilidade deletada com sucesso'
    else
      flash[:error] = 'Algo deu errado'
    end
    redirect_to character
  end

  private

  def skill_params
    # deveria estar no model?
    params[:skill][:effect_ids].reject!(&:empty?)
    params[:skill][:levels].reject!(&:empty?)
    params.require(:skill).permit(:name, :cost, :description, :picture, :kind,
                                  :order, effect_ids: [], levels: [])
  end
end

app/views/skills/_skill.html.erb
<div class='card mb-4 card-glow card-rounded <%= "skill-#{skill.order}" %>' 
       <%= 'id=cloth' if skill.cloth? %> >

<!-- Skill Header -->
  <div class="card-header">
    <div class="row">
    <!-- Skill Image and cost -->
      <div class="col-4 col-md-3 col-lg-2">
        <% if skill.picture.attached? %>
          <%= image_tag skill.picture, class: "border-black" %>
          <div class="bot-right">
            <%= image_pack_tag 'media/images/characters/energy_point.png', class: 'img-number' %>
            <span class="number"><%= skill.cost %></span>
          </div>
        <% end %>
      </div>

    <!-- Skill name and effects -->
      <div class="col-8 col-md-9 col-lg-10">  
        <h5 class="card-title"><%= skill.name %></h5>
          <ul class="skill-effects">
            <% skill.effects.each do |effect| %>
              <li><%= effect.name %></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>

<!-- Skill Body -->
  <div class="card-body">
    <!-- Skill description -->
    <p class="card-text">
      <%= skill.description %>
    </p>

    <!-- Skill levels -->
    <% if skill.levels.present? %>
      <hr>
      <ol>
        <% skill.levels.each do |level| %>
          <li><%= level %></li>
        <% end %>
      </ol>
    <% end %>

    <!-- Skill admin panel -->
    <div class="admin">
      <%= link_to 'Editar', edit_character_skill_path(@character, skill) %>
      <%= link_to 'Deletar', character_skill_path(@character, skill), method: :delete,
                  data: {confirm: "Remover essa skill?"}, class: 'text-danger float-right' %>
    </div>
  </div>
</div>

app/views/skills/edit.html.erb
<h1 class="text-center">Editando '<%= @skill.name %>' de <%= @character.name %></h1>
<%= render 'shared/errors', object: @skill %>
<div class="card text-dark">
  <div class="p-5">
    <%= form_for [@character, @skill] do |f| %>
      <div class="row">
        <div class="form-group col-10">
          <%= f.label :name, class: 'h3' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group col-2">
          <%= f.label :cost, class: 'h3' %>
          <%= f.text_field :cost, class: 'form-control' %>
        </div>

        <div class="form-group col-7">
          <%= f.label :picture, class: 'h3' %>
          <%= f.file_field :picture, class: 'form-control-file' %>
        </div>

        <div class="form-group col-2">
          <%= f.label :order, class: 'h3' %>
          <%= f.number_field :order, class: 'form-control' %>
        </div>

        <div class="form-group col-3">
          <%= f.label :kind, class: 'h3' %>
          <%= f.collection_select :kind, Skill.kinds, :first, :first, {}, class: 'form-control' %>
        </div>

        <div class="form-group col-12">
          <%= f.label :description, class: 'h3' %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <h3 class="my-3">Efeitos:</h3>
        <div style='columns: 4;' class="col-12">
          <% if @effects %>
            <%= f.collection_check_boxes :effect_ids, @effects, :id, :name do |b| %>
              <div class="form-check">
                <%= b.check_box %>
                <%= b.label %>
              </div>
            <% end %>
          <% end %>
          <%= link_to 'Adicionar mais efeitos', new_effect_path %>
        </div>

        <h3 class="my-3">Skill ups: </h3>
        <ol class="col-12">
        <% if @skill.levels.present? %>
            <% @skill.levels.each do |level| %>
              <li class="form-group">
                <%= text_area_tag "skill[levels][]", level, class: 'form-control m-2' %>
              </li>
            <% end %>
        <% else %>
          <li> <%= text_area_tag "skill[levels][]", nil, class: 'form-control m-2' %> </li>
          <li> <%= text_area_tag "skill[levels][]", nil, class: 'form-control m-2' %> </li>
          <li> <%= text_area_tag "skill[levels][]", nil, class: 'form-control m-2' %> </li>
          <li> <%= text_area_tag "skill[levels][]", nil, class: 'form-control m-2' %> </li>
          <li> <%= text_area_tag "skill[levels][]", nil, class: 'form-control m-2' %> </li>
        <% end %>
      </ol>

      </div>
    <%= link_to  "Voltar", character_path(@character), class: 'btn btn-primary' %>
    <%= f.submit 'Enviar', class: 'btn btn-success float-right' %>
    <% end %>
  </div>
</div>

app/views/skills/new.html.erb
<%= render 'shared/errors', object: @skill %>
<h1 class="text-center">Criando uma skill para <%= @character.name %> </h1>
<div class="card text-dark">
  <div class="p-5">
    <%= form_for @skill, url: character_skills_path do |f| %>
      <div class="row">
        <div class="form-group col-10">
          <%= f.label :name, class: 'h3' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group col-2">
          <%= f.label :cost, class: 'h3' %>
          <%= f.text_field :cost, class: 'form-control' %>
        </div>

        <div class="form-group col-7">
          <%= f.label :picture, class: 'h3' %>
          <%= f.file_field :picture, class: 'form-control-file' %>
        </div>

        <div class="form-group col-2">
          <%= f.label :order, class: 'h3' %>
          <%= f.number_field :order, class: 'form-control' %>
        </div>

        <div class="form-group col-3">
          <%= f.label :kind, class: 'h3' %>
          <%= f.collection_select :kind, Skill.kinds, :first, :first, {}, class: 'form-control' %>
        </div>

        <div class="form-group col-12">
          <%= f.label :description, class: 'h3' %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <h3 class="my-3">Efeitos:</h3>
        <div style='columns: 4;' class="col-12">
          <% if @effects %>
            <%= f.collection_check_boxes :effect_ids, @effects, :id, :name do |b| %>
              <div class="form-check">
                <%= b.check_box %>
                <%= b.label %>
              </div>
            <% end %>
          <% end %>
          <%= link_to 'Adicionar mais efeitos', new_effect_path %>
        </div>

        <h3 class="my-3">Skill ups:</h3>
        <% 1.upto(5) do |n| %>
          <div class="form-group col-12">
            <%= f.label :levels, "Skill lv. #{n}", value: n %>
            <%= f.text_field :levels, id: "skill_levels_#{n}", multiple: true, class: 'form-control m-2' %>
          </div>
        <% end %>

      </div>
    <%= link_to  "Voltar", character_path(@character), class: 'btn btn-primary' %>
    <%= f.submit 'Enviar', class: 'btn btn-success float-right' %>
    <% end %>
  </div>
</div>