config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/summon', to: 'home#summon'

  resources :ranks
  resources :constellations
  resources :effects
  resources :characters do
    resources :stats
    resources :skills
    resources :cosmos_sets
    get 'search', on: :collection
  end
  resources :banners, only: %i[index new create show]

  resources :cosmo_basics
  resources :cosmo_types
  resources :cosmos
  get 'eighth_sense', to: 'home#eighth_sense'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'summon/markers', to: 'summon#markers'
      get 'summon/random', to: 'summon#random'
    end
  end
end

app/views/shared/_errors.html.erb
<ul>
  <% if object.errors.any? %>
    <% object.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
	<% key = "success" if key == "notice" %>
	<% key = "danger" if key == "error" %>
  <div class="alert alert-<%= key %>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= value %></strong>
  </div>        
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-10">
        <h5>Links</h5>
        <ul class="list-unstyled text-small">
          <li><%= link_to 'Home', root_path, class: 'text-muted' %></li>
          <li><%= link_to 'Personagens', characters_path, class: 'text-muted' %></li>
          <li><%= link_to 'Login', new_user_session_path, class: 'text-muted' %></li>
          <li><%= link_to 'Registre-se', new_user_registration_path, class: 'text-muted' %></li>
        </ul>
      </div>
      <div class="col-2 float-right m-auto">
        <%= button_tag 'Topo', id: "to-top", class: 'btn btn-dark', title: 'Voltar ao topo' %>
      </div>
    </div>
    <hr>
    <small class="d-block mb-3 text-muted text-center">
      <%= link_to 'andre gomes', 'https://github.com/andrecego' %> © 2020 
    </small>
  </div>

</footer>

app/views/shared/_navbar.html.erb
<nav class="black-bg">
 <div class="container">
  <div class="menu-icon">
    <i class="fa fa-bars fa-2x" id="collapseMenu"></i>
  </div>
  <div class="logo">
    <%= link_to image_pack_tag('media/images/shared/logo.png', id: 'nav-logo'), root_path %>
  </div>
  <div class="nav-menu">
    <ul class="p-0">
      <li class="nav-item"> <%= link_to  "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to  "Summon", summon_path, class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to  "Personagens", characters_path, class: "nav-link" %></li>
      <li class="nav-item"> <%= link_to  "8º Sentido", eighth_sense_path, class: "nav-link" %></li>
      <% if current_user && current_user.admin? %>
        <li class="nav-item dropdown">
          <%= link_to 'Admin', '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdown', data: { toggle: 'dropdown'} %>
          <div class="dropdown-menu">
            <%= link_to "Constelações", constellations_path, class: "dropdown-item" %>
            <%= link_to "Banners", banners_path, class: "dropdown-item" %>
            <%= link_to "Ranks", ranks_path, class: "dropdown-item" %>
            <%= link_to "Efeitos de skill", effects_path, class: "dropdown-item" %>
            <%= link_to  'Cosmos', cosmos_path, class: 'nav-link' %>
            <%= link_to "Cosmos Base", cosmo_basics_path, class: "dropdown-item" %> 
            <%= link_to "Tipos de Cosmos", cosmo_types_path, class: "dropdown-item" %> 
          </div>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to('Login', new_user_session_path, class: 'nav-link') unless current_user %>
        <%= link_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete) if current_user %>
      </li>
    </ul>
  </div>
 </div>
</nav>