config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/summon', to: 'home#summon'

  resources :ranks
  resources :constellations
  resources :effects
  resources :characters do
    resources :stats
    resources :skills
    resources :cosmos_sets
    get 'search', on: :collection
  end
  resources :banners, only: %i[index new create show]

  resources :cosmo_basics
  resources :cosmo_types
  resources :cosmos
  get 'eighth_sense', to: 'home#eighth_sense'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'summon/markers', to: 'summon#markers'
      get 'summon/random', to: 'summon#random'
    end
  end
end

app/models/character.rb
# frozen_string_literal: true

class Character < ApplicationRecord
  belongs_to :rank
  belongs_to :constellation
  has_one_attached :picture
  has_many :stats, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :cosmos_sets, dependent: :destroy
  has_and_belongs_to_many :banners
  validates :name, :constellation_id, :rank_id, presence: true

  def uniq_name
    "#{name} - #{constellation.name}"
  end
end

app/controllers/characters_controller.rb
# frozen_string_literal: true

class CharactersController < ApplicationController
  before_action :authenticate_admin, only: %i[new create edit update destroy]

  include Pagy::Backend

  def index
    @pagy, @characters = pagy_countless(Character.all.order(name: :asc),
                                        items: 12,
                                        link_extra: 'data-remote="true"')
  end

  def search
    character_search_and_order
    if params[:rank_id].present?
      @characters = @characters.where(rank_id: params[:rank_id])
    end
    @pagy, @characters = pagy_countless(
      @characters, items: 12, link_extra: 'data-remote="true"'
    )
    respond_to do |format|
      format.js { render 'search' }
    end
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      flash[:success] = 'Personagem salvo com êxito'
      redirect_to @character
    else
      flash[:error] = 'Não foi possível cadastrar o personagem'
      render :new
    end
  end

  def show
    @character = Character.find(params[:id])
    @skills = @character.skills.order(order: :asc, kind: :desc)
    @stats = @character.stats
    @cosmos_sets = @character.cosmos_sets
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update(character_params)
      flash[:success] = 'Personagem atualizado com êxito'
      redirect_to @character
    else
      flash[:error] = 'Algo deu errado'
      render 'edit'
    end
  end

  def destroy
    @character = Character.find(params[:id])
    if @character.destroy
      flash[:success] = 'Personagem apagado com êxito'
    else
      flash[:error] = 'Houve um erro ao apagar'
    end
    redirect_to characters_path
  end

  private

  def character_params
    params.require(:character).permit(:name, :rank_id, :constellation_id,
                                      :picture)
  end

  def character_search_and_order
    @characters = if params[:q]
                    Character.where('name ILIKE ?', "%#{params[:q]}%")
                  else
                    Character.all
                  end
    @characters = if params[:order].present?
                    @characters.joins(:stats).where(stats: { kind: 'default' })
                               .order("#{order_sanitizer} DESC")
                  else
                    @characters.order(name: :asc)
                  end
  end

  def order_sanitizer
    if %w[health patk pdef matk mdef speed].include?(params[:order])
      return params[:order]
    end

    'health'
  end
end

app/views/characters/_admin_panel.html.erb
<div class="card-glow mb-4">
  <div class="admin p-3">
    <h3 class="text-center">Painel Admin</h3>
    <hr class="gradient">
    <li><%= link_to 'Editar Personagem', edit_character_path(@character) %></li>
    <li><%= link_to 'Remover Personagem', character_path(@character), method: :delete,
                    data: {confirm: 'Remover o personagem e todas skills?'}, class: 'text-danger' %></li>

    <li><%= link_to 'Cadastrar Status', new_character_stat_path(@character) %></li>

    <% if @stats.default.present? %>
      <li><%= link_to 'Editar Status Padrão', edit_character_stat_path(@character, @stats.default.first) %></li>
      <li><%= link_to 'Deletar Status Padrão', character_stat_path(@character, @stats.default.first), method: :delete,
                      data: { confirm: 'Remover esses status?' }, class: 'text-danger' %></li>
    <% end %>

    <% if @stats.cloth.present? %>
      <li><%= link_to 'Editar Status Cloth', edit_character_stat_path(@character, @stats.cloth.first) %></li>
      <li><%= link_to 'Deletar Status Cloth', character_stat_path(@character, @stats.cloth.first), method: :delete,
                      data: { confirm: 'Remover esses status?' }, class: 'text-danger' %></li>
    <% end %>
  </div>
</div>

app/views/characters/_character.html.erb
<div class="col-6 col-md-4 col-lg-3 my-3">
  <%= link_to character do %>
    <%= image_tag(character.picture, class: 'img-fluid', title: character.name, alt: character.name) %>
  <% end %>
</div>

app/views/characters/_form.html.erb
<%= form_with model: character, local: true do |f| %>

  <div class="row">
    <div class="form-group col-lg-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group col-lg-2">
    <%= f.label :rank_id, 'Rank' %>
    <%= f.collection_select :rank_id, Rank.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="form-group col-lg-4">
    <%= f.label :constellation_id %>
    <%= f.collection_select :constellation_id, Constellation.all, :id, :name, {}, class: 'form-control' %>
    </div>

    <div class="form-group col-lg-6">
    <%= f.label :picture, 'Foto' %>
    <%= f.file_field :picture, class: 'form-control-file' %>
    </div>
  </div>

  <%= link_to 'Voltar', characters_path, class: 'btn btn-danger' %>
  <%= f.submit 'Enviar', class: 'btn btn-success float-right' %>
<% end %>

app/views/characters/_next_link.html.erb
<%== pagy_next_link(@pagy, '', 'id="next_link" style="display: none;"') %>

app/views/characters/edit.html.erb
<h1>Editando <%= @character.name %></h1>
<%= render  "form", character: @character %>

app/views/characters/index.html.erb
<!-- <h1>Listagem de todos personagens</h1> -->
<%= link_to("Cadastrar novo personagem", new_character_path, class: 'admin') %>

<br>

<div class="p-2">
    <div class="row">
      <div class="form-group col-lg-2 col-4">
        <!-- collection_ranks, :first, :second, ao inves de Rank.all para adicionar 'Todos' -->
      <%= collection_select(nil, :rank_id, collection_ranks, :first, :second, { selected: '0'}, {class: 'form-control', id: 'rank_id'}) %>
      </div>
      <div class="form-group col-lg-4 col-8">
      <%= select_tag :order, options_for_select([['Pontos de Vida', 'health'], ['Ataque Físico', 'patk'], ['Defesa Física', 'pdef'], ['Ataque Cósmico', 'matk'], ['Defesa Cósmica', 'mdef'], ['Velocidade', 'speed']]), 
                     { prompt: 'Ordenar por...', class: 'form-control', selected: params[:order], id: 'order' } %>
      </div>
      <div class="form-group col-lg-6">
        <%= search_field_tag :q, params[:q], class: 'form-control search-field', placeholder: 'Buscar Personagem', id: 'q' %>
      </div>
    </div>
</div>

<div class="row" id="characters-grid">
  <%= render @characters %>
</div>
<%= content_tag(:div, render('next_link'), id: 'div_next_link') %>

app/views/characters/index.js.erb
$('#characters-grid').append("<%= j(render @characters)%>");
$('#div_next_link').html("<%= j(render 'next_link') %>");

app/views/characters/new.html.erb
<h1>Cadastrar um novo Personagem</h1>
<%= render 'shared/errors', object: @character %>
 <%= render  "form", character: @character %>

app/views/characters/search.js.erb
if ( "<%= @pagy.page == 1 %>" == 'true' ) { $('#characters-grid').html(""); }
$('#characters-grid').append("<%= j(render @characters)%>");
$('#div_next_link').html("<%= j(render 'next_link') %>");

app/views/characters/show.html.erb
<h1 class="text-center"><%= @character.name %></h1>


<div class="d-flex row">

  <div class="col-md-4" id="character-card">


    <div class="card card-glow card-char mb-4">
      <div class="row">

        <div class="char-img col-6 col-md-12">

          

          <% if @character.picture.attached? %>

          <!-- Character Portrait Box -->
          <div class="char-portrait-box" style="position: relative;">
            <!-- Character Portrait Image -->
            <%= image_tag @character.picture, class: 'card-img-top' %>

            <!-- Cloth Repair Button -->
            <% if @character.skills.any?(&:cloth?) %>
              <%= button_tag class: 'cloth-button', id: 'cloth-button', title:'Cloth Repair' do %>
                <div class="cloth-toggle" id="cloth-toggle">
                  <%= inline_svg_pack_tag 'media/images/characters/cloth.svg' %>
                </div>
              <% end %>
            <% end %>
            <!-- /Cloth Repair Button -->
          </div>
          <!-- /Character Portrait Box -->
          <% end %>
        </div>



        <div class="div-table row col-6 col-md-12">
          <%= render 'stats/stats', stats: @stats %>

          <div class="tr">
            <div class="td"><%= image_pack_tag 'media/images/characters/constellation.png', title: 'Constelação', size: 50 %><span>Constelação:</span></div>
            <div class="td"> <%= @character.constellation.name %></div>
          </div>

        </div>
      </div>
    </div>
    <%= render 'characters/admin_panel' %>

    <%= render 'cosmos_sets/cosmos_sets', cosmos_sets: @cosmos_sets %>

  </div>

  <div class="col-md-8">
    <%= render @skills %>
    <%= link_to  "Cadastrar nova skill", new_character_skill_path(@character), class: 'admin' %>
  </div>
</div>